### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by axwell** [blockbridge/blockbridge-simulator#1]
Hi i'm trying to install this but i get:

curl -sSL https://get.blockbridge.com/container | sh
latest: Pulling from blockbridge/simulator-up
Digest: sha256:239332e49df6d0006c9d1a1cd82fee73f02015fc123c30e61b5e4088114dfa20
Status: Image is up to date for blockbridge/simulator-up:latest
standard_init_linux.go:190: exec user process caused "exec format error"

Can you help ?

**Comment by srust** [comment]
Hi @axwell !

Are you running on arm or x86? It only supports x86_64 at the moment.

Can you share the output of `uname -a` on the host running docker?

Thanks!

**Comment by axwell** [comment]
Ah.. that makes sens. I'm on armv7l
When will be available on arm, i would like to give it a try.

**Comment by srust** [comment]
Great! Thanks for confirming. Closing this issue.
